"""
Reporting Service

Compiles text, metrics, and visualization artifacts into professional
Markdown, PDF, and PowerPoint reports. Handles uploading to MinIO.
"""

from __future__ import annotations

import io

import structlog
from fpdf import FPDF
from jinja2 import Template

from core.storage.minio import ensure_bucket_exists, minio_client

# Fallback imports
try:
    from pptx import Presentation
except ImportError:
    Presentation = None  # type: ignore

logger = structlog.get_logger(__name__)


class ReportingService:
    """Service for generating comprehensive reports."""

    def __init__(self, bucket_name: str = "reports"):
        self.bucket_name = bucket_name
        if minio_client is not None:
            try:
                ensure_bucket_exists(self.bucket_name)
            except Exception as e:
                logger.warning("reporting.bucket.failed", error=str(e))

    def generate_markdown(self, title: str, narrative: str, key_findings: list[str]) -> str:
        """
        Generate a Markdown report using a Jinja2 template.
        """
        template_str = """# {{ title }}

## Executive Summary
{{ narrative }}

## Key Findings
{% for finding in key_findings %}
- {{ finding }}
{% endfor %}
"""
        template = Template(template_str)
        return template.render(
            title=title,
            narrative=narrative,
            key_findings=key_findings,
        )

    def export_to_pdf(self, title: str, narrative: str, key_findings: list[str]) -> bytes | None:
        """
        Generate a clean PDF report using fpdf2.
        """
        try:
            pdf = FPDF()
            pdf.add_page()

            # Title
            pdf.set_font("helvetica", "B", 24)
            pdf.cell(0, 20, title, new_x="LMARGIN", new_y="NEXT", align="C")
            pdf.ln(10)

            # Executive Summary
            pdf.set_font("helvetica", "B", 16)
            pdf.cell(0, 10, "Executive Summary", new_x="LMARGIN", new_y="NEXT")
            pdf.set_font("helvetica", "", 12)
            pdf.multi_cell(0, 8, narrative)
            pdf.ln(10)

            # Key Findings
            pdf.set_font("helvetica", "B", 16)
            pdf.cell(0, 10, "Key Findings", new_x="LMARGIN", new_y="NEXT")
            pdf.set_font("helvetica", "", 12)
            for finding in key_findings:
                pdf.multi_cell(0, 8, f"\u2022 {finding}")

            return pdf.output()
        except Exception as e:
            logger.error("reporting.pdf.failed", error=str(e))
            return None

    def export_to_pptx(self, title: str, narrative: str, key_findings: list[str]) -> bytes | None:
        """
        Generate a PowerPoint presentation.
        """
        if Presentation is None:
            logger.warning("reporting.pptx.skipped", reason="python-pptx not installed")
            return None

        try:
            prs = Presentation()

            # Title Slide
            title_slide_layout = prs.slide_layouts[0]
            slide = prs.slides.add_slide(title_slide_layout)
            title_shape = slide.shapes.title
            subtitle_shape = slide.placeholders[1]
            title_shape.text = title
            subtitle_shape.text = "Generated by Cerebrum AI"

            # Executive Summary Slide
            bullet_slide_layout = prs.slide_layouts[1]
            slide = prs.slides.add_slide(bullet_slide_layout)
            shapes = slide.shapes
            title_shape = shapes.title
            body_shape = shapes.placeholders[1]
            title_shape.text = "Executive Summary"
            tf = body_shape.text_frame
            tf.text = narrative[:1000]  # truncate if too long

            # Findings Slide
            slide = prs.slides.add_slide(bullet_slide_layout)
            shapes = slide.shapes
            title_shape = shapes.title
            body_shape = shapes.placeholders[1]
            title_shape.text = "Key Findings"
            tf = body_shape.text_frame
            for finding in key_findings[:5]:  # Max 5 bullets for readability
                p = tf.add_paragraph()
                p.text = finding
                p.level = 0

            stream = io.BytesIO()
            prs.save(stream)
            return stream.getvalue()
        except Exception as e:
            logger.error("reporting.pptx.failed", error=str(e))
            return None

    def upload_report_to_minio(
        self, data: bytes | str, object_name: str, content_type: str
    ) -> str | None:
        """
        Upload the generated report to MinIO.
        """
        if minio_client is None:
            logger.warning("reporting.upload.skipped", reason="MinIO not configured")
            return None

        try:
            if isinstance(data, str):
                data = data.encode("utf-8")

            stream = io.BytesIO(data)
            size = len(data)

            minio_client.put_object(
                bucket_name=self.bucket_name,
                object_name=object_name,
                data=stream,
                length=size,
                content_type=content_type,
            )

            logger.info("reporting.upload.success", object_name=object_name)
            return f"/api/storage/{self.bucket_name}/{object_name}"
        except Exception as e:
            logger.error("reporting.upload.failed", error=str(e), object_name=object_name)
            return None
